"""added category, modified models

Revision ID: f8d5487c6440
Revises: b2d7e30e8b69
Create Date: 2025-09-05 22:27:08.360149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d5487c6440'
down_revision = 'b2d7e30e8b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_categories_name', ['name'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
